# Generated by Django 2.0.1 on 2018-02-06 20:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('magnet_v030', '0003_auto_20180127_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='authors',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='dataset',
            name='full_title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='dataset',
            name='journal',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dataset',
            name='link_to_pubmed',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='publication_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
