# Generated by Django 2.0.1 on 2018-02-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magnet_v030', '0005_auto_20180206_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='ensembl',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='gene',
            name='gene_name',
            field=models.CharField(max_length=50),
        ),
    ]
