# Generated by Django 2.0.7 on 2018-07-13 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magnet_v030', '0006_auto_20180219_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gene',
            name='ensembl',
        ),
    ]
