# Generated by Django 2.0.7 on 2018-07-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magnet_v030', '0008_auto_20180713_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
